In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet 
from sklearn.metrics import mean_squared_error 

In [2]:
data = pd.read_csv ("C:\\Thanusha\\Python\\ML master class\\Regularization\\Data\\Boston.csv")

In [3]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
x= data.iloc[:,:12].values
y= data.iloc[:,12].values

In [9]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [7]:
m1= LinearRegression()
m2= Ridge(alpha=1)
m3= Lasso(alpha=1)
m4= ElasticNet(alpha=1)

In [8]:
m1.fit(x_train,y_train)
m2.fit(x_train,y_train)
m3.fit(x_train,y_train)
m4.fit(x_train,y_train)

ElasticNet(alpha=1)

In [9]:
m1.coef_

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [10]:
m2.coef_

array([-0.12233832,  0.04609301, -0.0098171 , -8.64343893,  3.81854443,
       -0.00952306, -1.29823342,  0.24385986, -0.01267859, -0.99836523,
        0.00913742, -0.50051639])

In [11]:
m3.coef_

array([-0.05889028,  0.05317657, -0.        , -0.        ,  0.67954962,
        0.01684077, -0.6487664 ,  0.198738  , -0.01399421, -0.86421958,
        0.00660309, -0.73120957])

In [12]:
m4.coef_

array([-0.07922321,  0.05637835, -0.02484651, -0.        ,  0.84270351,
        0.01551814, -0.75788431,  0.22869565, -0.01471232, -0.85689217,
        0.00690502, -0.71471227])

In [13]:
yp1 = m1.predict(x_test)
yp2 = m2.predict(x_test)
yp3 = m3.predict(x_test)
yp4 = m4.predict(x_test)

In [14]:
print(np.sqrt(mean_squared_error(y_test,yp1)))
print(np.sqrt(mean_squared_error(y_test,yp2)))
print(np.sqrt(mean_squared_error(y_test,yp3)))
print(np.sqrt(mean_squared_error(y_test,yp4)))

5.849124083786667
5.905162730945171
6.457561211475197
6.376937515586476


In [15]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [16]:
x.shape

(506, 12)

In [17]:
arr = np.array([0.09632,28.0,2.91,0.938,3.575,55.2,5.0900,3,297,15.8,366.96,3.98]).reshape(1,12)

In [18]:
m1.predict(arr)

array([12.07599024])

In [24]:
m2.predict(arr)

array([15.42583369])

In [25]:
m3.predict(arr)

array([29.66943031])

In [26]:
m4.predict(arr)

array([29.14485454])